/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoclica.visao;

import br.com.projetoclica.controle.AgendaControl;
import br.com.projetoclica.controle.AgendaMedicoControl;
import br.com.projetoclica.controle.ConexaoBD;
import br.com.projetoclica.controle.AgendamentoControl;
import br.com.projetoclica.controle.MedicoControl;
import br.com.projetoclica.controle.PacienteControl;
import br.com.projetoclica.model.AgendamentoModel;
import br.com.projetoclica.model.MedicoModel;
import br.com.projetoclica.model.PacienteModel;
import br.com.projetoclica.model.TabelaModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Jovino
 */
public class FormAgendaMedico extends javax.swing.JFrame {
    private AgendamentoModel agendamentoModel = new AgendamentoModel();
    private ArrayList dados = new ArrayList();
    private  ArrayList<AgendamentoModel> listaAgendamentos = new ArrayList<>();
    private ArrayList<PacienteModel> listaPacientes = new ArrayList<>();
    private AgendaControl agendaControl = new AgendaControl();
    private String dataPesquisada = "";
    private ArrayList<MedicoModel> listaMedicos = new ArrayList<>();
    private MedicoControl medicoControl = new MedicoControl();
    private AgendaMedicoControl agendaMedicoControl = new AgendaMedicoControl();
    private MedicoModel medicoModel = new MedicoModel();
    /**
     * Creates new form TelaFormMedico
     */
    public FormAgendaMedico() {
        initComponents();
        preencherTabela("", null);
        preencherListaMedicos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePacienteAgenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAtender = new javax.swing.JButton();
        jTextFieldMotivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMedicos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButtonBuscar = new javax.swing.JButton();
        jLabelCadastroMedico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablePacienteAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePacienteAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacienteAgendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablePacienteAgenda);

        jLabel1.setText("Agenda de Pacientes:");

        jButtonAtender.setText("ATENDER");
        jButtonAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtenderActionPerformed(evt);
            }
        });

        jLabel2.setText("Motivo:");

        jComboBoxMedicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Médico:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAtender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMotivo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addComponent(jButtonAtender)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jLabelCadastroMedico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCadastroMedico.setText("AGENDA MÉDICO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabelCadastroMedico)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCadastroMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        setSize(new java.awt.Dimension(633, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTablePacienteAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacienteAgendaMouseClicked
        agendamentoModel = listaAgendamentos.get(jTablePacienteAgenda.getSelectedRow());
        jTextFieldMotivo.setEditable(false);
        jTextFieldMotivo.setText("");
        jTextFieldMotivo.setText(agendamentoModel.getMotivoAgendamento());
        System.out.println(agendamentoModel.getMotivoAgendamento());
    }//GEN-LAST:event_jTablePacienteAgendaMouseClicked

    private void jButtonAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtenderActionPerformed
        agendamentoModel = listaAgendamentos.get(jTablePacienteAgenda.getSelectedRow());
        agendamentoModel.setSituacaoAgendamento(jButtonAtender.getText());
//        agendaControl.alterarSituacao(agendamentoModel);
        FormConsulta formulario = new FormConsulta(agendamentoModel, agendamentoModel.getCodMedicoAgendamento());
        formulario.setVisible(true);
    }//GEN-LAST:event_jButtonAtenderActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        if(jComboBoxMedicos.getSelectedIndex()==0){
            medicoModel = null;
        }else{
            medicoModel = listaMedicos.get(jComboBoxMedicos.getSelectedIndex()-1);
            System.out.println(medicoModel.getNome());
        }
        preencherTabela("", medicoModel);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    public void preencherTabela(String medico, MedicoModel medicoModel){
        dados = agendaMedicoControl.preencherTabela(medico, medicoModel);
        
        if(dados != null){listaAgendamentos = agendaMedicoControl.buscarAgendamento(medico, medicoModel);}
        String[] colunas = new String[]{
            "Nome", "RG", "Telefone", "Situação", "Turno", "MotivoAgendamento"
        };
        TabelaModel modeloTabela = new TabelaModel(dados, colunas);
        jTablePacienteAgenda.setModel(modeloTabela);
        jTablePacienteAgenda.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTablePacienteAgenda.getColumnModel().getColumn(0).setResizable(true);
        jTablePacienteAgenda.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTablePacienteAgenda.getColumnModel().getColumn(1).setResizable(true);
        jTablePacienteAgenda.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTablePacienteAgenda.getColumnModel().getColumn(2).setResizable(true);
        jTablePacienteAgenda.getColumnModel().getColumn(3).setPreferredWidth(50);
        jTablePacienteAgenda.getColumnModel().getColumn(3).setResizable(true);
        jTablePacienteAgenda.getColumnModel().getColumn(4).setPreferredWidth(50);
        jTablePacienteAgenda.getColumnModel().getColumn(4).setResizable(true);

        jTablePacienteAgenda.getTableHeader().setReorderingAllowed(true);
        
//        jTableAgenda.setAutoResizeMode(jTableAgenda.AUTO_RESIZE_ALL_COLUMNS);
        jTablePacienteAgenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgendaMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtender;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxMedicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCadastroMedico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTablePacienteAgenda;
    private javax.swing.JTextField jTextFieldMotivo;
    // End of variables declaration//GEN-END:variables

    
    private void preencherListaMedicos() {
        listaMedicos = medicoControl.buscarMedicos("");
        System.out.println(listaMedicos.size());
        jComboBoxMedicos.removeAllItems();
        jComboBoxMedicos.addItem(" - ");
        for(MedicoModel medico : listaMedicos){
            jComboBoxMedicos.addItem(medico.getNome());
        }
    }

}
