/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoclica.visao;

import br.com.projetoclica.controle.ConexaoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Jovino
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    FormMedico medico = new FormMedico();
    FormUsuario usuario = new FormUsuario();
    FormAgendamento agendamento = new FormAgendamento();
    FormAgenda agenda = new FormAgenda();
    FormAgendaMedico agendaMedico = new FormAgendaMedico();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(String Usuario) {
        initComponents();
        conecta.conexao();
        jLabelUsuario.setText(Usuario);
    }

    private TelaPrincipal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInterno = new javax.swing.JPanel();
        jLabelCadastro = new javax.swing.JLabel();
        jLabelAgenda = new javax.swing.JLabel();
        jButtonAgenda = new javax.swing.JButton();
        jButtonCadPacientes = new javax.swing.JButton();
        jButtonCadEnfermeiras = new javax.swing.JButton();
        jButtonCadMedico = new javax.swing.JButton();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonFecharBemVindo = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        fundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemMedicos = new javax.swing.JMenuItem();
        jMenuItemPacientes = new javax.swing.JMenuItem();
        jMenuItemEnfermeira = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInterno.setLayout(null);

        jLabelCadastro.setText("Cadastro:");
        jPanelInterno.add(jLabelCadastro);
        jLabelCadastro.setBounds(10, 10, 70, 20);

        jLabelAgenda.setText("Agenda:");
        jPanelInterno.add(jLabelAgenda);
        jLabelAgenda.setBounds(10, 210, 70, 14);

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projetoclica/imagens/Agenda.png"))); // NOI18N
        jButtonAgenda.setText("Agendar");
        jButtonAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAgenda.setVerifyInputWhenFocusTarget(false);
        jButtonAgenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonAgenda);
        jButtonAgenda.setBounds(10, 230, 110, 150);

        jButtonCadPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projetoclica/imagens/cadPacientes.png"))); // NOI18N
        jButtonCadPacientes.setText("Pacientes");
        jButtonCadPacientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadPacientes.setVerifyInputWhenFocusTarget(false);
        jButtonCadPacientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelInterno.add(jButtonCadPacientes);
        jButtonCadPacientes.setBounds(230, 40, 110, 160);

        jButtonCadEnfermeiras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projetoclica/imagens/icon-infermeira.png"))); // NOI18N
        jButtonCadEnfermeiras.setText("Enfermeira");
        jButtonCadEnfermeiras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadEnfermeiras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelInterno.add(jButtonCadEnfermeiras);
        jButtonCadEnfermeiras.setBounds(120, 40, 110, 160);

        jButtonCadMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projetoclica/imagens/CadMedicos.png"))); // NOI18N
        jButtonCadMedico.setText("Médico");
        jButtonCadMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadMedico.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicoActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonCadMedico);
        jButtonCadMedico.setBounds(10, 40, 110, 160);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projetoclica/imagens/internalframe.png"))); // NOI18N
        jPanelInterno.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(0, 0, 630, 380);

        jInternalFrameBemVindo.getContentPane().add(jPanelInterno);
        jPanelInterno.setBounds(0, 60, 630, 380);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 12, 260, 30);

        jButtonFecharBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projetoclica/imagens/exit.png"))); // NOI18N
        jButtonFecharBemVindo.setBorder(null);
        jButtonFecharBemVindo.setContentAreaFilled(false);
        jButtonFecharBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharBemVindoActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonFecharBemVindo);
        jButtonFecharBemVindo.setBounds(570, 10, 40, 40);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(10, 60, 650, 480);

        jLabelUsuario.setText("jLabel2");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(10, 550, 60, 14);

        fundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/projetoclica/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(fundoPrincipal);
        fundoPrincipal.setBounds(0, 0, 670, 570);

        jMenuCadastros.setText("Cadastros");

        jMenuItemMedicos.setText("Médicos");
        jMenuItemMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMedicosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemMedicos);

        jMenuItemPacientes.setText("Pacientes");
        jMenuCadastros.add(jMenuItemPacientes);

        jMenuItemEnfermeira.setText("Enfermeira");
        jMenuCadastros.add(jMenuItemEnfermeira);

        jMenuItemUsuarios.setText("Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemUsuarios);

        jMenuItem2.setText("Agenda");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItem2);

        jMenuBar1.add(jMenuCadastros);

        jMenuRelatorios.setText("Relatorios");

        jMenuItem4.setText("Pacientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuRelatorios.add(jMenuItem4);

        jMenuBar1.add(jMenuRelatorios);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenu1.setText("Agenda");

        jMenuItem1.setText("Buscar Agenda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Buscar por Médico");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(689, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharBemVindoActionPerformed
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonFecharBemVindoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
        jInternalFrameBemVindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jButtonCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicoActionPerformed
        jMenuItemMedicosActionPerformed(evt);
    }//GEN-LAST:event_jButtonCadMedicoActionPerformed

    private void jMenuItemMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMedicosActionPerformed
        if(verificarAcesso()){  
            if(medico==null){
                medico = new FormMedico();
                medico.setVisible(true);
            }else{
                medico.setVisible(true);
                medico.setResizable(false);
            }          
        }else{
            JOptionPane.showMessageDialog(null, "Você não possui permissão para essa operação");
        }

    }//GEN-LAST:event_jMenuItemMedicosActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        if(verificarAcesso()){       
            if(usuario==null){
                usuario = new FormUsuario();
                usuario.setVisible(true);
            }else{
                usuario.setVisible(true);
                usuario.setResizable(false);
            }          
        }else{
            JOptionPane.showMessageDialog(null, "Você não possui permissão para essa operação");
        }
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
         if(verificarAcesso()){       
            if(agendamento==null){
                agendamento = new FormAgendamento();
                agendamento.setVisible(true);
            }else{
                agendamento.setVisible(true);
                agendamento.setResizable(false);
            }          
        }else{
            JOptionPane.showMessageDialog(null, "Você não possui permissão para essa operação");
        }
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(verificarAcesso()){       
            if(agenda==null){
                agenda = new FormAgenda();
                agenda.setVisible(true);
            }else{
                agenda.setVisible(true);
                agenda.setResizable(false);
            }          
        }else{
            JOptionPane.showMessageDialog(null, "Você não possui permissão para essa operação");
        }  
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(verificarAcesso()){       
            if(agendamento==null){
                agendamento = new FormAgendamento();
                agendamento.setVisible(true);
            }else{
                agendamento.setVisible(true);
                agendamento.setResizable(false);
            }          
        }else{
            JOptionPane.showMessageDialog(null, "Você não possui permissão para essa operação");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(verificarAcesso()){       
            if(agendaMedico==null){
                agendaMedico = new FormAgendaMedico();
                agendaMedico.setVisible(true);
            }else{
                agendaMedico.setVisible(true);
                agendaMedico.setResizable(false);
            }          
        }else{
            JOptionPane.showMessageDialog(null, "Você não possui permissão para essa operação");
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        
        int confirma = JOptionPane.showConfirmDialog(null, "Você deseja imprim"
                + "ir?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            String src = "C:/Users/Jovino.NB-JUNIOR/Documents/NetBeansProjects/ProjetoClinica/src/br/com/projetoclica/relatorio/relatorio.jasper";
            JasperPrint jasperPrint = null;
            
            try {
                jasperPrint = JasperFillManager.fillReport(src, null, conecta.conexao());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage()+"\n Erro ao gerar Relatório");
            }
            
            JasperViewer jasperViewer = new JasperViewer(jasperPrint, false);
            jasperViewer.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private boolean verificarAcesso() {
        StringBuilder sql = new StringBuilder();
        sql.append("SELECT * FROM ");
        sql.append("usuarios ");
        sql.append("WHERE \"loginUsuario\"='");
        sql.append(jLabelUsuario.getText());
        sql.append("'");
        conecta.executaSQL(sql.toString());
        
        try {
            conecta.rs.first();
            String tipoUsuario = conecta.rs.getString("tipoUsuario").trim();
            System.out.println(tipoUsuario);
            if(tipoUsuario.equals("Administrador")){
                return true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Você não possui permissão para essa operação \n"+ex.getMessage() );
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundoPrincipal;
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonCadEnfermeiras;
    private javax.swing.JButton jButtonCadMedico;
    private javax.swing.JButton jButtonCadPacientes;
    private javax.swing.JButton jButtonFecharBemVindo;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemEnfermeira;
    private javax.swing.JMenuItem jMenuItemMedicos;
    private javax.swing.JMenuItem jMenuItemPacientes;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInterno;
    // End of variables declaration//GEN-END:variables
}
